spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_cosmetics?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8081
logging.level.org.springframework.security=DEBUG
cloudinary.cloudName=dh3mjr24e
cloudinary.apiKey=199751558116365
cloudinary.apiSecret=n3T2hIbr88BWIncj8CPPP8RStqI
vnpay.tmnCode=15DAHBZW
vnpay.hashSecret=9LE1X7OC157YBE75R2PZZYAU52YPG8EX
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8081/api/payment/vnpay-return